version: '3'

services:

  db:
    #    image: postgres:16.8-alpine3.21
    build:
      context: ./postgres
      target: postgres_with_script
    container_name: platform-repo
    restart: unless-stopped
#    restart: on-failure
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: platform-repo
#      POSTGRES_USER:
#      POSTGRES_PASSWORD:
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "user"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    volumes:
      #      - db-data:/var/lib/postgresql/data
      #      - ./postgres/:/docker-entrypoint-initdb.d/
      - ./postgres/platform_repo:/var/lib/postgresql/data/pgdata
#    expose:
#      - 5432:5432
    ports:
      - 5432:5432
    networks:
      platform-network:
        ipv4_address: 172.18.1.2

  platform:
    build:
      context: ./platform
      target: platform_with_jar
#    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: tomcat, hide, psql, jpa_update, log
    volumes:
      - ./platform/log:/var/log/platform
#      - ./platform/properties:platform/log:/opt/platform/extracted/application/BOOT-INF/classes
    ports:
      - 8080:8080
    networks:
      platform-network:
        ipv4_address: 172.18.1.3
#    depends_on:
#      db:
#        condition: service_healthy
#        restart: true

#volumes:
# certbot-etc:
#  wordpress:
#  platform-repo:

networks:
  platform-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
