version: '3'

services:

  db:
    build:
      context: ./postgres
      target: postgres_with_script
    container_name: platform-repo
    restart: unless-stopped
    expose:
      - 5432:5432
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/platform_repo:/var/lib/postgresql/data/pgdata
    networks:
      platform-network:
        ipv4_address: 172.18.1.2

  docker-with-spring-profile:
    build:
      context: ./platform
      target: platform_with_jar
    environment:
      SPRING_PROFILES_ACTIVE: test
    networks:
      platform-network:
        ipv4_address: 172.18.1.3
    depends_on:
      db:
        condition: service_healthy
        restart: true

networks:
  platform-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
