version: '3'
services:
  db:
#    image: postgres:16.8-alpine3.21
    build:
      context: ./postgres
      target: postgres_with_script
    container_name: platform-repo
    restart: unless-stopped
    expose:
      - 5432
    command: -p 5432
    ports:
      - 5432:5432
#    env_file: .env
    environment:
      - POSTGRES_DB=platform-repo
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - PGDATA=/var/lib/postgresql/data/pgdata
    secrets:
      - postgres-user
      - postgres-password
    volumes:
#      - db-data:/var/lib/postgresql/data
#      - ./postgres/:/docker-entrypoint-initdb.d/
      - ./postgres/platform_repo:/var/lib/postgresql/data/pgdata
    networks:
      - platform-network
secrets:
  postgres-user:
    file: .postgres-user
  postgres-password:
    file: .postgres-password
#volumes:
# certbot-etc:
#  wordpress:
#  platform-repo:
networks:
  platform-network:
    driver: bridge
